export const SET_JOURNEYS = "SET_JOURNEYS";
export const SET_FILTERED_JOURNEYS = "SET_FILTERED_JOURNEYS";
export const SET_PLACES = "SET_PLACES";
export const SET_SEASONS = "SET_SEASONS";
export const SET_ACTIVITIES = "SET_ACTIVITIES";
export const SET_DURATIONS = "SET_DURATIONS";
export const SET_DAYS = "SET_DAYS";
export const SET_MONTHS = "SET_MONTHS";

export const SET_SELECTED_DIRECTIONS = "SET_SELECTED_DIRECTIONS";

export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const SET_FILTERING_STATUS = "SET_FILTERING_STATUS";

export const SET_ROADBOOK = "SET_ROADBOOK";

export const SET_JOURNEY_DIALOG_STATUS = "SET_JOURNEY_DIALOG_STATUS";
export const SET_HELP_DIALOG_STATUS = "SET_HELP_DIALOG_STATUS";

